### ISSUE TITLE
Updated DTB/DTS still need to export gpio 37 to use USB.

### ISSUE THREAD

**Issue by hiskang** [rogers0/OpenLinkstation#10] opened 2016-01-23 13:33 UTC
> With updated DTB, which is already committed, you don't have to export gpio pin anymore.
> USB gets working from very beginning.

> Updated DTB/DTS can be downloaded from: https://github.com/rogers0/OpenLinkstation/tree/master/1_debootstrap/dtb

I tried your updated DTB on my LS-WSXL but USB didn't work from the beginning and exporting gpio 37 is still required as below log. 

I'm not sure why.  Using ls-wxl DTB on LS-WSXL may cause this...  In the case of your original DTB around Oct 2015, I had to make some change to turn off blinking blue LED, because my daughter didn't like that:)
I saw your latest commit has new LS-WSXL dedicated DT. If you don't have LS-WSXL let me try to them.

root@LS-WSXLE12:~# uname -a
Linux LS-WSXLE12 4.3.0-0.bpo.1-kirkwood #1 Debian 4.3.3-7~bpo8+1 (2016-01-19) armv5tel GNU/Linux

root@LS-WSXLE12:~# lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

root@LS-WSXLE12:~# echo 37 >/sys/class/gpio/export
root@LS-WSXLE12:~# echo out > /sys/class/gpio/gpio37/direction
root@LS-WSXLE12:~# echo 1 > /sys/class/gpio/gpio37/value

root@LS-WSXLE12:~# lsusb
Bus 001 Device 002: ID 2019:ed17 PLANEX GW-USValue-EZ 802.11n Wireless Adapter [Realtek RTL8188CUS]
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by rogers0** [comment] 2016-01-23 13:53
On Sat, Jan 23, 2016 at 10:33 PM, hiskang <notifications@github.com> wrote:
>
> With updated DTB, which is already committed, you don't have to export gpio pin anymore
> USB gets working from very beginning
>
> Updated DTB/DTS can be downloaded from: https://githubcom/rogers0/OpenLinkstation/tree/master/1_debootstrap/dtb
>
> I tried your updated DTB on my LS-WSXL but USB didn't work from the beginning and exporting gpio 37 is still required as below log

Thanks for your feedback!

How do you use my updated DTB? Did you change the config for flash-kernel?
I mean you need to copy the dtb to /etc/flash-kerne/dtbs/, then run flash-kernel command to update the boot image.

> I'm not sure why Using ls-wxl DTB on LS-WSXL may cause this In the case of your original DTB around Oct 2015, I had to make some change to turn off blinking blue LED, because my daughter didn't like that:)
> I saw your latest commit has new LS-WSXL dedicated DT If you don't have LS-WSXL let me try to them

LS-WSXL just doesn't have HDD error LEDs & FAN control. Basically they're the same.
Of course I checked them all before submitting to upstream.
Both are working fine on gpio of LEDs/FAN/USB.

> root@LS-WSXLE12:~# uname -a
> Linux LS-WSXLE12 430-0bpo1-kirkwood #1 Debian 433-7~bpo8+1 (2016-01-19) armv5tel GNU/Linux
>
> root@LS-WSXLE12:~# lsusb
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 20 root hub
>
> root@LS-WSXLE12:~# echo 37 >/sys/class/gpio/export
> root@LS-WSXLE12:~# echo out > /sys/class/gpio/gpio37/direction
> root@LS-WSXLE12:~# echo 1 > /sys/class/gpio/gpio37/value
>
> root@LS-WSXLE12:~# lsusb
> Bus 001 Device 002: ID 2019:ed17 PLANEX GW-USValue-EZ 80211n Wireless Adapter [Realtek RTL8188CUS]
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 20 root hub

With updated DTB, the export of 37 gpio pin will always fail. Because it's already used system.

Cheers,
Roger

**Comment by rogers0** [comment] 2016-01-23 15:43
I commit all newly accepted DTS/DTB to github:
- https://github.com/rogers0/OpenLinkstation/tree/master/1_debootstrap/dtb

Remember to update flash-kernel's machine db (/etc/flash-kernel/db), because the dtb filename has been changed.

**Comment by hiskang** [comment] 2016-01-25 11:55
Hi Rogers, Thanks for updating your github.

I might did any mistake... May I ask your way how to to replace dtb in detail?

Regards,
hiska

**Comment by rogers0** [comment] 2016-01-25 12:31
1. copy updated dtb to /etc/flash-kernel/dtbs/

2. confirm the filename (if updated)  is in /etc/flash-kernel/db 
Machine: Buffalo Linkstation LS-WXL/WSXL
Kernel-Flavors: kirkwood
DTB-Id: <updated dtb filename>

3. run command: flash-kernel
    if you installed a few kernels, you may need to specify the version, such as
      flash-kernel --force 3.16.0-4-kirkwood
or
      flash-kernel --force 4.3.0-0.bpo.1-kirkwood

4. confirm the log output, and there should be one line telling you which dtb is using, such as:
flash-kernel: appending /etc/flash-kernel/dtbs/kirkwood-linkstation-lswsxl.dtb to kernel

5. reboot
6. if anything wrong (bricked?), you need to open the box and mount sdX1 on other Linux desktop, and update the symbol links:
    ln -sf uImage.flash-kernel.bak uImage.buffalo
    ln -sf initrd.flash-kernel.bak initrd.buffalo
so you can boot by your old images...

Good luck!

**Comment by rogers0** [comment] 2016-02-26 14:30
I guess the issue is solved, so closing this.

**Closed by rogers0** 2016-02-26 14:30 UTC
